-- quiz_seed.sql
-- 주식 1~5 학습 문서 기반 퀴즈 (5파트 × 20문항 = 100문항)

DROP TABLE IF EXISTS quiz_questions;

CREATE TABLE quiz_questions (
  day INTEGER NOT NULL,
  question_no INTEGER NOT NULL,
  source_doc TEXT NOT NULL,
  topic TEXT NOT NULL,
  question TEXT NOT NULL,
  choice_1 TEXT NOT NULL,
  choice_2 TEXT NOT NULL,
  choice_3 TEXT NOT NULL,
  choice_4 TEXT NOT NULL,
  answer INTEGER NOT NULL,
  explanation TEXT NOT NULL,
  PRIMARY KEY (day, question_no)
);

-- 주식 1: 병합 문서 03, 04, 05 → docs/03.md
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 1, '03', '경기사이클', '경기사이클 4단계를 순서대로 나열한 것은?', '회복→확장→후퇴→수축', '확장→회복→수축→후퇴', '수축→후퇴→확장→회복', '후퇴→수축→회복→확장', 0, '경기사이클은 회복(recovery) → 확장(expansion) → 후퇴(slowdown) → 수축(contraction) 순으로 순환한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 2, '03', 'Porter 5 Forces', 'Porter의 5가지 경쟁요인(Five Forces)에 포함되지 않는 것은?', '신규 진입자 위협', '대체재 위협', '정부 규제 강도', '구매자 교섭력', 2, 'Porter 5 Forces는 신규 진입자, 대체재, 구매자 교섭력, 공급자 교섭력, 기존 경쟁자 간 경쟁강도로 구성된다. 정부 규제는 직접 포함되지 않는다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 3, '03', 'DART', 'DART(Data Analysis, Retrieval and Transfer System)는 어떤 기관이 운영하는가?', '한국거래소(KRX)', '금융감독원(FSS)', '기획재정부', '한국은행', 1, 'DART는 금융감독원이 운영하는 전자공시시스템으로 상장기업의 사업보고서, 분기보고서 등을 공시한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 4, '03', '선행지표', '다음 중 경기 선행지표에 해당하는 것은?', '실업률', '주식시장 지수', 'GDP 성장률', '소비자물가지수', 1, '주가지수는 기업의 미래 이익 기대를 반영하므로 경기 선행지표로 분류된다. 실업률과 GDP는 동행 또는 후행지표이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 5, '03', 'Porter 5 Forces', '구매자 교섭력이 강해지는 조건은?', '구매자 수가 많고 개별 구매량이 적을 때', '구매자 수가 적고 대량 구매할 때', '전환비용이 높을 때', '공급자가 독점일 때', 1, '구매자 교섭력은 구매자 수가 적고 대량 구매 시, 전환비용이 낮을수록 강해진다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 6, '03', 'DART', '기업이 DART에 공시해야 하는 주요 정기 보고서가 아닌 것은?', '사업보고서(연간)', '분기보고서(1·3분기)', '반기보고서(2분기)', '일간 매출 보고서', 3, 'DART 정기공시는 사업보고서(연간), 반기보고서(반기), 분기보고서(1·3분기) 등이다. 일간 매출 보고서는 공시 의무가 없다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 7, '03', '후행지표', '다음 중 경기 후행지표에 해당하는 것은?', '건축 허가 건수', '장단기 금리차', '실업률', '제조업 신규 수주', 2, '실업률은 기업이 경기 악화 후 감원을 결정하는 데 시간이 걸리므로 경기 후퇴 이후에 반응하는 후행지표이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 8, '03', 'Porter 5 Forces', '진입장벽이 높을 때 신규 진입자 위협은?', '매우 높다', '낮아진다', '변화 없다', '대체재 위협과 동일해진다', 1, '진입장벽(규모의 경제, 특허, 브랜드, 초기 자본 등)이 높으면 신규 경쟁자가 시장에 들어오기 어려워 기존 기업의 경쟁 위협이 낮아진다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 9, '03', 'DART', '유상증자 공시를 주목해야 하는 이유는?', '이익이 늘기 때문', '주식 수 증가로 기존 주주의 지분이 희석될 수 있기 때문', '배당이 자동으로 증가하기 때문', '주가가 항상 상승하기 때문', 1, '유상증자는 신주를 발행하여 자금을 조달하므로 주식 수가 늘어 기존 주주의 지분율이 낮아지는 희석 효과가 발생한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 10, '03', '통화량', 'M1 통화량에 포함되지 않는 것은?', '현금', '요구불예금', '수시입출금식 예금', '2년 이상 정기예금', 3, 'M1은 현금과 즉시 인출 가능한 요구불예금, 수시입출금 예금 등 협의의 통화를 포함한다. 2년 이상 정기예금은 M2에 포함된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 11, '03', 'SWOT', 'SWOT 분석에서 "O"가 의미하는 것은?', '운영 효율성(Operational)', '기회(Opportunity)', '조직 구조(Organization)', '외부 위협(Outside threat)', 1, 'SWOT는 Strengths(강점), Weaknesses(약점), Opportunities(기회), Threats(위협)의 약자이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 12, '03', 'DART', '자사주 취득 공시가 주가에 긍정적으로 해석되는 이유는?', '기업이 직원 급여를 올리기 때문', '유통 주식 수 감소로 주당 가치가 높아질 수 있기 때문', '부채가 줄어들기 때문', '매출이 자동으로 늘기 때문', 1, '자사주 취득은 시장에서 유통되는 주식 수를 줄여 주당 순이익(EPS)을 높이고 주주가치를 제고하는 효과가 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 13, '03', '통화량', 'M2는 M1에 어떤 항목을 추가한 것인가?', '해외 보유 달러', '2년 미만 정기예금, MMF 등 준통화', '회사채', '주식', 1, 'M2는 M1에 2년 미만 정기예금, MMF, 금융채 등 단기 저축성 예금과 단기 금융상품을 더한 광의의 통화지표이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 14, '03', 'SWOT', 'SWOT 분석에서 내부 요인에 해당하는 것은?', '경쟁사의 신제품 출시', '정부 규제 완화', '자사의 기술력과 브랜드 가치', '글로벌 수요 증가', 2, 'SWOT에서 강점(S)과 약점(W)은 기업 내부 요인이고, 기회(O)와 위협(T)은 외부 환경 요인이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 15, '03', 'DART', '수주 공시가 중요한 산업으로 가장 적절한 것은?', '소매유통', '조선·건설·방산', '식품', '금융', 1, '수주 공시는 미래 매출 예상액을 나타내므로 수주 기반으로 운영되는 조선·건설·방산 기업에서 특히 중요하다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 16, '03', 'QE', '양적완화(QE, Quantitative Easing)의 핵심 메커니즘은?', '기준금리를 급격히 인상한다', '중앙은행이 국채 등 자산을 매입하여 시중 유동성을 공급한다', '정부가 세금을 인하하여 소비를 촉진한다', '시중은행이 대출 금리를 자율적으로 낮춘다', 1, 'QE는 중앙은행이 국채·MBS 등을 매입하여 본원통화를 늘리고 시중에 유동성을 직접 공급하는 비전통적 통화정책이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 17, '03', 'PEST', 'PEST 분석의 4가지 요소가 올바르게 짝지어진 것은?', '정치, 경제, 사회, 기술', '생산, 효율, 시스템, 기술', '가격, 환경, 서비스, 기술', '정치, 에너지, 시스템, 기업', 0, 'PEST는 Political(정치), Economic(경제), Social(사회문화), Technological(기술) 환경을 분석하는 프레임워크이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 18, '03', 'Peer Comparison', 'Peer Comparison(동종업체 비교) 분석의 목적은?', '단일 기업의 절대적 가치만 평가', '동일 산업 내 경쟁사와 비교하여 상대적 가치와 강점을 파악', '기업의 역사적 성과만 분석', '경쟁사 기밀 정보 수집', 1, 'Peer Comparison은 동일 산업 내 유사 기업들과 재무지표, 밸류에이션 등을 비교하여 상대적 매력도를 평가하는 분석 방법이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 19, '03', 'QT', '양적긴축(QT, Quantitative Tightening)이란?', '중앙은행이 보유 자산을 매각하거나 만기 상환 후 재투자하지 않아 유동성을 흡수하는 정책', '정부가 재정지출을 늘리는 정책', '기준금리를 제로로 낮추는 정책', '시중은행 지급준비율을 낮추는 정책', 0, 'QT는 QE의 반대로 중앙은행이 보유 채권을 매각하거나 만기 도래분을 재투자하지 않아 시중 유동성을 흡수한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 20, '03', 'PEST', 'PEST 분석에서 고령화 트렌드는 어느 요소에 해당하는가?', '정치(Political)', '경제(Economic)', '사회(Social)', '기술(Technological)', 2, '고령화는 인구구조 변화로 사회문화적 환경(Social) 요소에 해당한다.');

-- 주식 2: 병합 문서 06, 07, 08 → docs/04.md
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 1, '04', '손익계산서', '손익계산서에서 매출총이익(Gross Profit)의 계산식은?', '매출액 - 판관비', '매출액 - 매출원가', '영업이익 + 감가상각비', '당기순이익 + 이자비용', 1, '매출총이익 = 매출액 - 매출원가로, 제품 생산 원가를 제외한 기본 수익성을 나타낸다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 2, '04', '현금흐름표', '현금흐름표의 3가지 활동 구분이 올바른 것은?', '영업·투자·재무', '생산·판매·관리', '유입·유출·순변동', '단기·중기·장기', 0, '현금흐름표는 영업활동(CFO), 투자활동(CFI), 재무활동(CFF)의 3가지 섹션으로 구성된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 3, '04', '티커', '한국 상장주식의 종목코드 형식은?', '알파벳 1~4자리', '6자리 숫자', '알파벳과 숫자의 혼합', '3자리 숫자', 1, '한국 주식 종목코드는 6자리 숫자로 구성된다. 예: 삼성전자 005930, 카카오 035720.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 4, '04', '손익계산서', '영업이익의 계산식은?', '매출총이익 - 판매비와관리비', '매출액 - 매출원가', '당기순이익 + 법인세', '매출총이익 + 영업외이익', 0, '영업이익 = 매출총이익 - 판매비와관리비(판관비)로, 영업활동에서 발생한 순수 이익이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 5, '04', '현금흐름표', '영업활동 현금흐름(CFO)이 높다는 것의 의미는?', '부채가 많다는 뜻이다', '본업에서 현금을 잘 창출하고 있다는 신호이다', '투자를 많이 한다는 뜻이다', '배당금을 많이 준다는 뜻이다', 1, 'CFO가 높으면 주된 영업활동에서 현금이 충분히 창출되어 자금 조달 없이도 사업을 운영할 수 있음을 나타낸다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 6, '04', '티커', '미국 상장주식의 티커(ticker) 형식은?', '6자리 숫자', '1~4자리 알파벳', '국가코드 + 숫자', '숫자 + 알파벳 혼합', 1, '미국 주식 티커는 거래소별로 1~4자리 알파벳으로 구성된다. 예: AAPL(애플), TSLA(테슬라), AMZN(아마존).');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 7, '04', '손익계산서', '당기순이익(Net Income)과 영업이익의 차이는?', '동일하다', '당기순이익은 영업이익에서 이자, 세금 등을 추가 반영한 최종 이익이다', '영업이익이 항상 더 작다', '당기순이익은 세전 이익이다', 1, '영업이익은 영업활동에서의 이익이고, 당기순이익은 여기에 영업외손익(이자, 투자손익), 법인세를 모두 반영한 최종 이익이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 8, '04', '현금흐름표', '이상적인 성숙 기업의 현금흐름 패턴은?', 'CFO 마이너스, CFI 플러스, CFF 플러스', 'CFO 플러스, CFI 마이너스, CFF 마이너스', 'CFO 플러스, CFI 플러스, CFF 플러스', 'CFO 마이너스, CFI 마이너스, CFF 마이너스', 1, '성숙 기업은 영업에서 현금을 벌고(CFO+), 미래를 위해 투자하며(CFI-), 부채 상환과 배당을 지급(CFF-)하는 패턴이 이상적이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 9, '04', 'PER', 'PER(Price-to-Earnings Ratio)의 계산식은?', '주가 / 주당 매출액', '주가 / 주당 순이익(EPS)', '시가총액 / 순자산', '영업이익 / 주가', 1, 'PER = 주가 / EPS(주당순이익) = 시가총액 / 당기순이익으로 기업의 이익 대비 주가 수준을 나타낸다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 10, '04', '매출총이익률', '매출총이익률(Gross Margin)이 높다는 것의 의미는?', '비용 전체가 낮다', '제품의 가격 결정력이 강하거나 원가 효율성이 높다', '영업이익이 반드시 높다', '순이익이 반드시 높다', 1, '매출총이익률이 높다는 것은 원가 대비 높은 가격을 받을 수 있는 가격 결정력이나 원가 절감 능력이 있음을 의미한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 11, '04', 'FCF', '잉여현금흐름(FCF, Free Cash Flow)의 계산식은?', '영업이익 - 법인세', 'CFO - 자본적지출(Capex)', '당기순이익 + 감가상각비', '매출액 - 변동비', 1, 'FCF = 영업활동 현금흐름(CFO) - 자본적지출(Capex)로 기업이 사업 유지·확장 투자 후 자유롭게 사용할 수 있는 현금이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 12, '04', 'PER', 'PER이 낮다는 것이 반드시 저평가를 의미하지 않는 이유는?', '이익이 크기 때문', '이익 성장률이 낮거나 기업에 구조적 문제가 있을 수 있기 때문', '주가가 낮기 때문', '배당을 많이 주기 때문', 1, 'PER이 낮아도 성장이 정체되거나 실적 악화 위험이 있으면 저평가가 아닌 "저평가 함정(value trap)"일 수 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 13, '04', '고정비/변동비', '매출이 증가해도 총액이 변하지 않는 비용은?', '변동비', '고정비', '한계비용', '재료비', 1, '고정비는 생산량이나 매출 변화에 관계없이 일정하게 발생하는 비용이다. 임대료, 감가상각비, 고정 급여 등이 해당된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 14, '04', 'FCF', 'FCF가 높은 기업이 할 수 있는 활동이 아닌 것은?', '배당 지급', '자사주 매입', '부채 상환', '법인세 면제', 3, 'FCF가 높으면 주주환원(배당·자사주), 부채 상환, 추가 투자 등 재무적 유연성이 커진다. 법인세 면제는 FCF와 무관하다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 15, '04', 'PBR', 'PBR(Price-to-Book Ratio)의 계산식은?', '주가 / EPS', '주가 / BPS(주당순자산)', '시가총액 / 연 매출', 'EV / EBITDA', 1, 'PBR = 주가 / BPS(주당순자산) = 시가총액 / 순자산으로 자산 대비 주가 수준을 나타낸다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 16, '04', '고정비/변동비', '단위당 생산량에 비례하여 증가하는 비용은?', '고정비', '감가상각비', '변동비', '임대료', 2, '변동비는 생산량이나 매출에 비례하여 증가하는 비용이다. 재료비, 판매 수수료, 포장비 등이 대표적이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 17, '04', 'DCF', 'DCF(Discounted Cash Flow) 가치평가의 핵심 개념은?', '과거 이익을 평균하여 가치를 산정한다', '미래에 발생할 현금흐름을 현재가치로 할인하여 기업 가치를 구한다', '시가총액과 장부가를 비교한다', '업종 평균 PER를 적용한다', 1, 'DCF는 기업이 미래에 창출할 잉여현금흐름(FCF)을 적정 할인율(WACC)로 현재가치화하여 내재가치를 산출하는 방법이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 18, '04', 'PBR', 'PBR이 1 미만이라는 것의 의미는?', '기업의 시장가치가 장부상 순자산보다 낮다', '기업이 적자이다', '주가가 고평가되어 있다', '부채가 자본보다 많다', 0, 'PBR < 1은 주가가 1주당 순자산(장부가)보다 낮게 평가되고 있다는 의미로, 저평가 신호일 수 있으나 사업 수익성 문제일 수도 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 19, '04', '손익분기점', '손익분기점(BEP, Break-Even Point)의 정의는?', '최대 이익이 발생하는 매출 수준', '총 수익과 총 비용이 같아지는 매출 수준', '영업이익률이 최대인 수준', '변동비가 0이 되는 수준', 1, 'BEP는 총수익(매출)과 총비용이 일치하여 이익도 손실도 없는 매출 수준으로 고정비 ÷ (단위당 판매가 - 단위당 변동비)로 계산된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (2, 20, '04', 'DCF', 'DCF 분석에서 할인율이 높아지면 기업 가치는?', '증가한다', '변화 없다', '감소한다', '두 배가 된다', 2, '할인율이 높을수록 미래 현금흐름의 현재가치가 줄어들어 DCF로 산출한 기업 내재가치가 낮아진다.');

-- 주식 3: 병합 문서 09, 16 → docs/05.md
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 1, '05', '추세분석', '상승 추세선을 올바르게 설명한 것은?', '연속적인 고점을 연결한 선', '연속적인 저점(higher lows)을 연결한 선', '이동평균선 위에 그은 선', '52주 고점들을 연결한 선', 1, '상승 추세선은 차트에서 연속적으로 높아지는 저점(higher lows)들을 연결하여 그리며 지지선 역할을 한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 2, '05', 'KOSPI 상위 종목', 'docs/16.md 기준 KOSPI 거래량 1위 종목으로 옳은 것은?', '삼성전자', 'SK하이닉스', '현대차', '카카오', 1, '2026-05-27 기준 KOSPI 거래량 상위 1위는 삼성전자(005930)로, 반도체/전자 업종에 해당한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 3, '05', '지지/저항', '지지선(Support)이란?', '주가가 상승할 때 저항을 받는 가격대', '주가가 하락하다가 매수세가 유입되어 반등하는 가격대', '52주 신고가 수준', '이동평균선', 1, '지지선은 과거에 주가가 여러 번 하락을 멈추고 반등한 가격대로, 매수세가 집중되는 영역이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 4, '05', '종목코드', 'SK하이닉스의 KRX 종목코드로 옳은 것은?', '005930', '000660', '005490', '035720', 2, 'SK하이닉스의 종목코드는 000660이며, KOSPI 거래량 상위 2위 반도체 업종이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 5, '05', '지지/저항', '저항선이 하향 돌파된 후 저항이 지지로 바뀌는 현상은?', '골든크로스', '갭', '역할전환(Role Reversal)', '다이버전스', 2, '역할전환은 과거의 지지선이 저항선으로, 혹은 저항선이 지지선으로 기능이 바뀌는 현상이다. 기술적 분석의 핵심 원리 중 하나이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 6, '05', 'KOSPI 업종', 'KOSPI 거래량 상위 3위인 POSCO홀딩스(005490)의 업종으로 옳은 것은?', 'IT/플랫폼', '자동차', '철강/소재', '반도체', 3, 'POSCO홀딩스는 철강/소재 업종으로, KOSPI 거래량 기준 3위에 해당한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 7, '05', '이동평균', '단기(MA5)가 장기(MA20)를 위로 교차할 때 나타나는 신호는?', '데드크로스', '골든크로스', '다이버전스', '피보나치 되돌림', 1, '골든크로스는 단기 이동평균선이 장기 이동평균선을 아래에서 위로 교차하는 현상으로 매수 신호로 해석된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 8, '05', 'KOSDAQ 상위 종목', 'KOSDAQ 거래량 1위 종목과 업종의 조합으로 옳은 것은?', 'HLB — 바이오/항암', '에코프로 — 지주/양극재', '에코프로비엠 — 양극재', '알테오젠 — 바이오/SC', 3, 'KOSDAQ 거래량 1위는 에코프로비엠(247540)이며 양극재 업종이다. 에코프로(086520)는 2위 지주/양극재이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 9, '05', '이동평균', '데드크로스(Dead Cross)란?', '단기 MA가 장기 MA를 위로 교차', '단기 MA가 장기 MA를 아래로 교차', '주가가 MA200 위로 상승', '볼린저밴드 수축', 1, '데드크로스는 단기 이동평균이 장기 이동평균을 위에서 아래로 교차하는 현상으로 매도 신호로 해석된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 10, '05', 'HBM3E 사양', 'HBM3E 메모리의 최대 대역폭으로 옳은 것은?', '800GB/s', '1.2TB/s', '2TB/s', '6.4TB/s', 2, 'HBM3E는 최대 1.2TB/s 대역폭과 9Gbps 이상 핀 속도를 제공하며, AI 가속기와 HPC에 활용된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 11, '05', '이동평균', 'MA200(200일 이동평균선)의 의미는?', '단기 모멘텀 지표', '장기 추세를 나타내며 주가의 장기 지지/저항 역할', '거래량 이동평균', '볼린저밴드 중선', 1, 'MA200은 약 1년간의 평균 주가로 장기 추세를 보여주며 기관·장기 투자자들이 중요하게 참고하는 지지/저항선이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 12, '05', 'HBM4 사양', 'HBM4의 인터페이스 비트 수로 옳은 것은?', '512-bit', '1024-bit', '2048-bit', '4096-bit', 3, 'HBM4는 2048-bit 인터페이스를 사용하여 최대 2TB/s급 대역폭을 제공하는 차세대 AI 메모리이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 13, '05', 'RSI', 'RSI(상대강도지수)의 기본 계산 기간은?', '5일', '9일', '14일', '20일', 2, 'RSI는 기본적으로 14일을 기준으로 계산하며, 최근 14일간 상승폭 평균과 하락폭 평균의 비율을 이용한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 14, '05', 'LPDDR5 사양', 'LPDDR5의 최대 전송 속도로 옳은 것은?', '3.2Gbps', '4.8Gbps', '6.4Gbps', '9.6Gbps', 3, 'LPDDR5의 최대 전송 속도는 6.4Gbps로, LPDDR4 대비 50% 이상 향상된 스마트폰·엣지 디바이스용 저전력 메모리이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 15, '05', 'RSI', 'RSI가 70 이상일 때 일반적인 의미는?', '과매도 구간', '중립 구간', '과매수 구간', '추세 전환 확정', 2, 'RSI 70 이상은 과매수(Overbought) 구간으로 단기 조정 가능성을 시사한다. 30 이하는 과매도(Oversold) 구간이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 16, '05', 'HBM4 전력효율', 'HBM4의 전력 효율 향상률(기존 대비)로 옳은 것은?', '10% 이상', '20% 이상', '30% 이상', '50% 이상', 3, 'HBM4는 전력 효율이 기존 대비 30% 이상 향상되어 차세대 AI 데이터센터와 대규모 모델 학습에 최적화되었다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 17, '05', 'MACD', 'MACD의 계산 방법은?', 'EMA(12) - EMA(26)', 'EMA(26) - EMA(12)', 'MA(10) × MA(20)', 'RSI(14) - RSI(9)', 0, 'MACD = EMA(12) - EMA(26)으로 단기와 장기 지수이동평균의 차이를 나타내며 추세의 방향과 모멘텀을 분석한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 18, '05', 'pykrx 함수', 'pykrx에서 특정 날짜의 시장별 거래량 데이터를 조회할 때 사용하는 함수로 옳은 것은?', 'get_market_price_by_ticker', 'get_market_volume_ranking', 'get_market_trading_volume_by_ticker', 'get_stock_volume_by_market', 3, 'pykrx의 get_market_trading_volume_by_ticker(date, market="KOSPI")를 사용하면 특정 날짜의 시장별 거래량 데이터를 DataFrame으로 반환받을 수 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 19, '05', 'MACD', 'MACD 시그널선(Signal Line)이란?', 'MACD 자체', 'MACD의 9일 EMA', '거래량 가중 평균', 'RSI의 이동평균', 1, '시그널선은 MACD의 9일 지수이동평균(EMA)으로, MACD가 시그널선을 상향 돌파하면 매수, 하향 돌파하면 매도 신호로 해석한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (3, 20, '05', 'HBM3E 활용', 'HBM3E를 탑재한 대표적인 AI 가속기 GPU(NVIDIA 제품)로 옳은 것은?', 'RTX 4090', 'A100', 'V100', 'H100', 4, 'HBM3E는 NVIDIA H100과 AMD MI300 GPU에 활용되며, 대규모 AI 학습 및 슈퍼컴퓨터에 최적화되어 있다.');

-- 주식 4: 병합 문서 10, 11, 12, 13 → docs/06.md
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 1, '06', '캔들', '캔들차트에서 몸통(Body)은 무엇을 나타내는가?', '당일의 최고가와 최저가 범위', '당일 시가와 종가 사이의 범위', '거래량', '다음날 예상 가격', 1, '캔들 몸통은 시가(Open)와 종가(Close) 사이의 범위를 나타낸다. 종가 > 시가이면 양봉(상승), 종가 < 시가이면 음봉(하락)이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 2, '06', '주주 권리', '주주의 3대 권리가 올바르게 묶인 것은?', '경제적 권리, 경영 참여 권리, 정보 접근 권리', '배당권, 의결권, 환불권', '양도권, 분할권, 소각권', '설립권, 해산권, 청산권', 0, '주주의 3대 권리는 경제적 권리(배당, 잔여재산 분배), 경영 참여 권리(의결권, 주주제안권), 정보 접근 권리(재무제표 열람 등)이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 3, '06', '금융투자상품', '자본시장법상 금융투자상품의 핵심 정의 요소는?', '원금이 보장된다', '원금 손실 가능성이 있는 투자 계약', '이자가 발생한다', '정부가 보증한다', 1, '자본시장법은 투자원금 손실 가능성이 있는 금융상품을 금융투자상품으로 정의한다. 원금 보장 상품은 금융투자상품에 해당하지 않는다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 4, '06', 'ETF vs 펀드', 'ETF와 일반 펀드의 가장 큰 거래 방식의 차이는?', '동일하다', 'ETF는 거래소에서 실시간 매매, 일반 펀드는 운용사·판매사 경유 기준가로 매매', 'ETF는 기관만 거래 가능', '일반 펀드가 더 낮은 비용', 1, 'ETF는 주식처럼 거래소에서 실시간으로 매매되고, 일반 펀드는 판매사를 통해 기준가(NAV)로 다음날 처리된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 5, '06', '캔들', '캔들의 꼬리(Wick/Shadow)가 나타내는 것은?', '시가와 종가 사이의 범위', '당일 고가-저가 중 몸통 밖의 가격 범위', '다음날 예상 고가·저가', '이동평균과의 차이', 1, '위꼬리(upper shadow)는 고가에서 몸통(시가·종가 중 높은 쪽)까지, 아래꼬리(lower shadow)는 저가에서 몸통(낮은 쪽)까지의 범위이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 6, '06', '자사주', '자사주 소각의 주주가치 제고 효과는?', '총 자산 증가', '유통 주식수 감소 → EPS 증가 → 주당 가치 상승', '부채 감소', '매출 증가', 1, '자사주 소각은 발행 주식수를 영구적으로 줄여 EPS(주당순이익)를 높이고 주주 1인당 가치를 증가시키는 효과가 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 7, '06', '금융투자상품', '자본시장법상 증권과 파생상품의 주요 차이는?', '동일하다', '증권은 원금 초과 손실이 없으나 파생상품은 원금 초과 손실이 가능하다', '파생상품은 주식만 포함', '증권은 손실이 없다', 1, '자본시장법은 증권(지분증권, 채무증권 등)과 파생상품(선물, 옵션, 스왑)을 구분하며 파생상품은 원금 초과 손실 가능성이 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 8, '06', 'ETF vs 펀드', '일반 공모펀드 대비 ETF의 비용 측면 장점은?', 'ETF는 항상 무료', '보통 ETF의 총보수(TER)가 동일 유형의 일반 펀드보다 낮다', 'ETF는 세금이 없다', 'ETF는 판매사 수수료만 있다', 1, 'ETF는 패시브 운용이 많고 구조적으로 비용이 낮아 일반 공모펀드 대비 총보수가 낮은 경향이 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 9, '06', '캔들패턴', '도지(Doji) 캔들의 특징은?', '매우 긴 양봉', '시가와 종가가 같거나 거의 같아 몸통이 없는 캔들', '하단 꼬리만 있는 캔들', '거래량이 0인 캔들', 1, '도지는 시가와 종가가 같거나 매우 가까운 캔들로 매수·매도 세력의 균형을 나타내며 추세 전환 가능성을 시사한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 10, '06', '주주제안권', '소수주주가 주주제안권을 행사하기 위한 요건은?', '지분 0.1% 이상, 보유 기간 무관', '지분 1% 이상, 6개월 이상 보유', '지분 5% 이상, 1년 이상 보유', '단 1주 보유시도 가능', 1, '주주제안권은 발행주식 총수의 1% 이상을 6개월 이상 보유한 주주가 주주총회 안건을 제안할 수 있는 권리이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 11, '06', 'ETF 구조', 'ETF(Exchange Traded Fund)의 주요 특징은?', '거래소에서 거래 불가', '증권거래소에 상장되어 주식처럼 실시간 매매 가능한 펀드', '원금 보장 상품', '특정 기업의 주식만 담음', 1, 'ETF는 인덱스나 특정 자산을 추종하며 거래소에 상장되어 주식처럼 실시간으로 매매할 수 있는 펀드이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 12, '06', '괴리율', '괴리율(Premium/Discount)의 계산식은?', '(NAV - 시장가격) / NAV × 100', '(시장가격 - NAV) / NAV × 100', '추적오차 / NAV', '총보수 / NAV', 1, '괴리율 = (ETF 시장가격 - NAV) / NAV × 100으로 양수면 시장가가 NAV보다 높은 프리미엄, 음수면 디스카운트 상태이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 13, '06', '캔들패턴', '망치형(Hammer) 캔들이 강한 매수 신호로 해석되는 이유는?', '긴 위꼬리가 있어서', '하락 추세 말미에 나타나며 긴 아래꼬리가 매도 후 강한 매수세 유입을 나타내기 때문', '몸통이 크기 때문', '거래량이 낮기 때문', 1, '망치형은 하락 추세에서 장중 크게 하락했다가 매수세로 종가가 크게 회복된 형태로 반등 가능성을 시사한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 14, '06', '거래소', 'KOSPI, KOSDAQ, KONEX의 설명이 올바르게 짝지어진 것은?', 'KOSPI: 중소기업 전용, KOSDAQ: 대기업 전용, KONEX: 기술기업', 'KOSPI: 대기업 중심 주시장, KOSDAQ: 기술·벤처 중심, KONEX: 초기 중소·벤처기업', 'KOSPI: 코스닥과 동일, KONEX: 외국인 전용', 'KOSDAQ: 국채 시장, KONEX: 파생상품 시장', 1, 'KOSPI는 대기업 중심의 주시장, KOSDAQ은 기술·벤처 기업 중심, KONEX는 초기 중소·벤처기업을 위한 시장이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 15, '06', '펀드 구조', '개방형 펀드(Open-End Fund)의 특징은?', '설정액이 고정되어 있어 추가 매수 불가', '언제든지 추가 설정(매수)과 환매(매도)가 가능', '거래소에서만 매매', '만기가 고정됨', 1, '개방형 펀드는 투자자가 원할 때 수시로 가입(추가 설정)하거나 환매할 수 있어 설정액이 변동된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 16, '06', '괴리율', '괴리율이 크게 벌어지는 주요 원인은?', '수익률이 높기 때문', '거래량 부족이나 기초자산 시장 휴장 시 가격 발견이 어렵기 때문', '총보수가 낮기 때문', '상장폐지 임박', 1, '해외 자산 ETF에서 기초자산 시장이 휴장 중이거나 유동성이 부족할 때 괴리율이 크게 벌어질 수 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 17, '06', '캔들패턴', '역망치형(Inverted Hammer)과 망치형의 차이는?', '동일하다', '역망치형은 긴 위꼬리를 가지며 하락 추세 말미에 출현한다', '역망치형은 상승 추세에서만 나타난다', '역망치형은 음봉이다', 1, '역망치형은 위꼬리가 길고 하락 추세 말미에 나타나는 잠재적 반전 신호이다. 망치형은 아래꼬리가 길다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 18, '06', 'IPO', 'IPO(Initial Public Offering) 절차에서 수요예측(Book Building)의 목적은?', '공모가를 무작위로 설정하기 위해', '기관투자자 수요 조사를 통해 적정 공모가를 결정하기 위해', '소액투자자를 위한 배정', '청약 경쟁률을 높이기 위해', 1, '수요예측은 기관투자자들의 청약 희망 가격과 수량을 수집하여 공모가를 결정하는 과정이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 19, '06', '펀드 클래스', '펀드 클래스 A와 C의 차이는?', '동일하다', 'A클래스는 선취판매수수료가 있고 C클래스는 없지만 연간 판매보수가 더 높다', 'C클래스는 외국인 전용', 'A클래스만 기관투자자 대상', 1, 'A클래스는 가입 시 선취수수료를 내는 대신 연간 판매보수가 낮고, C클래스는 선취수수료 없이 연간 판매보수가 상대적으로 높다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (4, 20, '06', '추적오차', '추적오차(Tracking Error)란?', 'ETF 시장가격과 NAV의 차이', 'ETF 수익률과 기초지수 수익률의 차이', '총보수의 다른 표현', '배당수익률', 1, '추적오차는 ETF가 목표로 하는 기초지수 수익률과 실제 ETF 수익률 간의 차이를 나타내며 작을수록 지수를 잘 복제하고 있다는 의미이다.');

-- 주식 5: 병합 문서 14, 15 → docs/07.md
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 1, '07', 'MPT', '현대 포트폴리오 이론(MPT)에서 해리 마코위츠의 핵심 통찰은?', '수익을 최대화하면 위험도 최대가 된다', '분산투자를 통해 총 위험을 줄이면서 동일 기대수익을 달성할 수 있다', '모든 자산에 동일한 비중으로 투자해야 한다', '위험이 없는 포트폴리오를 만들 수 있다', 1, 'MPT의 핵심은 상관관계가 낮은 자산을 결합하면 개별 자산의 위험 합산보다 포트폴리오 전체 위험을 줄일 수 있다는 분산투자 원리이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 2, '07', '자산배분', '자산배분이 포트폴리오 성과의 몇 %를 결정한다고 알려져 있는가?', '약 40%', '약 60%', '약 90% 이상', '약 30%', 2, 'Brinson et al.(1986)의 연구에 따르면 포트폴리오 성과의 90% 이상이 자산배분(주식/채권/현금 비중 결정)에 의해 결정된다고 알려져 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 3, '07', 'MPT', '효율적 투자선(Efficient Frontier)에 있는 포트폴리오의 특징은?', '수익이 최대인 포트폴리오들', '동일한 위험 수준에서 최대 기대수익, 또는 동일한 기대수익에서 최소 위험인 포트폴리오들', '모든 자산을 포함한 포트폴리오', '무위험 자산만 포함한 포트폴리오', 1, '효율적 투자선은 주어진 위험 수준에서 달성 가능한 최대 기대수익을 제공하는 포트폴리오들의 집합이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 4, '07', '자산배분', '마코위츠가 말한 "유일한 공짜 점심(free lunch)"이란?', '무위험 수익을 얻는 것', '분산투자를 통해 수익 포기 없이 위험을 줄일 수 있다는 것', '고수익 자산에 집중 투자', '레버리지 사용', 1, '마코위츠는 상관관계가 낮은 자산들을 결합하면 개별 자산 합산보다 위험을 줄이면서 수익을 유지할 수 있는 분산투자를 "투자에서 유일한 공짜 점심"이라고 했다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 5, '07', 'CAGR', 'CAGR(연평균 복합 성장률)의 계산식은?', '(최종가치 - 초기가치) / 투자기간', '(최종가치 / 초기가치)^(1/투자기간) - 1', '초기가치 × (1 + 연이율)^n', '(최종가치 / 초기가치 - 1) × 투자기간', 1, 'CAGR = (최종가치 / 초기가치)^(1/n) - 1로 투자 기간 동안 매년 일정하게 성장했다고 가정한 등가 연평균 성장률이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 6, '07', '자산배분', '50% 손실 후 원금 회복을 위해 필요한 수익률은?', '50%', '75%', '100%', '150%', 2, '50% 손실로 자산이 반으로 줄면 원금 회복을 위해 남은 자산의 100% 수익이 필요하다. 이 비대칭성이 MDD 관리의 중요성을 보여준다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 7, '07', 'CAGR', 'CAGR이 단순 평균 수익률보다 더 의미 있는 성과 지표인 이유는?', '계산이 더 간단하기 때문', '변동성 효과를 고려한 복리 기준의 실질 연수익률을 나타내기 때문', '세금이 포함되기 때문', '단기 수익률을 잘 반영하기 때문', 1, 'CAGR은 투자 기간 동안 복리로 얼마나 성장했는지를 나타내어 연도별 수익률이 달라도 일관된 비교 기준을 제공한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 8, '07', 'MVO', 'MVO(Mean-Variance Optimization, 평균-분산 최적화)의 목적은?', '수익률 극대화만 추구', '주어진 기대수익률에서 분산(위험)을 최소화하거나 주어진 위험에서 기대수익을 최대화하는 포트폴리오 비중 도출', '단일 자산에 집중', '무위험 수익 확보', 1, 'MVO는 마코위츠의 효율적 투자선 도출을 위한 최적화 방법으로 입력 변수(기대수익률, 분산, 공분산)를 이용해 효율적 포트폴리오 비중을 계산한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 9, '07', 'MDD', 'MDD(Maximum Drawdown, 최대낙폭)란?', '투자 기간 중 최대 수익률', '특정 기간 내 고점 대비 최대 하락 폭', '변동성 지표', '최소 수익 달성 기간', 1, 'MDD = (저점 - 직전 고점) / 직전 고점으로 투자 기간 중 발생한 고점에서 저점까지의 최대 하락률이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 10, '07', 'MVO', 'MVO의 주요 실무적 한계점은?', '계산이 불가하다', '기대수익률 추정 오차에 매우 민감하여 입력값이 조금만 달라져도 결과가 크게 달라진다', '항상 낮은 수익률을 제공한다', '분산 효과가 없다', 1, 'MVO는 기대수익률 추정에 매우 민감하여 작은 추정 오차도 포트폴리오 비중을 극단적으로 변화시키는 "garbage in, garbage out" 문제가 있다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 11, '07', 'MDD', 'MDD가 50%이면 원금을 회복하기 위해 필요한 수익률은?', '50%', '100%', '150%', '200%', 1, '50% 손실 후 원금 회복을 위해서는 남은 자산의 100% 수익이 필요하다. 손실과 회복에 필요한 수익률은 비대칭적이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 12, '07', '블랙-리터만', '블랙-리터만(Black-Litterman) 모델의 핵심은?', '과거 수익률만 사용', '시장 균형 수익률(역최적화)을 출발점으로 하고 투자자의 전망(view)을 베이지안 방식으로 결합한다', '등가중 포트폴리오 구성', '레버리지를 최대화한다', 1, '블랙-리터만은 시장 포트폴리오에서 역으로 추론한 균형 기대수익률에 투자자의 주관적 전망을 결합하여 더 안정적인 포트폴리오를 도출하는 모델이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 13, '07', '샤프비율', '샤프비율(Sharpe Ratio)의 계산식은?', '(포트폴리오 수익률 - 무위험수익률) / 포트폴리오 표준편차', '포트폴리오 수익률 / MDD', '초과수익률 / 하방 표준편차', 'CAGR / |MDD|', 0, '샤프비율 = (Rp - Rf) / σp × √252로 무위험수익률을 초과하는 수익을 전체 변동성(표준편차)으로 나눈 위험 조정 수익률이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 14, '07', '블랙-리터만', '블랙-리터만 모델에서 "역최적화(reverse optimization)"란?', '포트폴리오 비중을 역으로 분산시키는 것', '시장 포트폴리오 비중과 공분산 행렬로부터 시장이 내포하는 균형 기대수익률을 역산하는 것', '손실을 최대화하는 방법', '레버리지를 줄이는 방법', 1, '역최적화는 시장 포트폴리오 비중이 효율적이라고 가정하고 공분산 행렬과 함께 시장이 암묵적으로 가정하는 기대수익률을 역으로 계산하는 방법이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 15, '07', '샤프비율', '샤프비율에서 √252를 곱하는 이유는?', '월간 수익률을 연간화하기 위해', '일별 수익률을 연간화하기 위해 (1년 거래일 약 252일)', '표준편차를 조정하기 위해', '무위험수익률을 반영하기 위해', 1, '일별 초과수익률과 일별 표준편차로 계산한 샤프비율을 연간 기준으로 환산하기 위해 √252(연간 거래일)를 곱한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 16, '07', 'Risk-Parity', '리스크 패리티(Risk Parity) 전략의 핵심 원칙은?', '모든 자산에 동일 금액 투자', '각 자산이 포트폴리오 전체 위험에 동등하게 기여하도록 비중을 설정', '가장 수익이 높은 자산에 집중', '채권에만 투자', 1, '리스크 패리티는 자산별 위험 기여도를 균등화하는 전략으로 변동성이 낮은 자산(채권)에는 더 높은 비중을, 변동성이 높은 자산(주식)에는 더 낮은 비중을 부여한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 17, '07', '소르티노비율', '소르티노비율(Sortino Ratio)이 샤프비율과 다른 점은?', '동일하다', '분모에 전체 변동성 대신 하방 변동성(하락 표준편차)만을 사용한다', '분자가 다르다', '연간화하지 않는다', 1, '소르티노비율 = (Rp - Rf) / σ_downside × √252로 투자자에게 실질적으로 불이익인 하락 변동성만을 리스크로 계산하는 개선된 위험 조정 수익률이다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 18, '07', 'Risk-Parity', '리스크 패리티 포트폴리오가 60/40 포트폴리오와 다른 점은?', '동일하다', '60/40은 금액 기준 배분이고 리스크 패리티는 위험 기여도 기준으로 각 자산의 비중을 결정한다', '리스크 패리티는 주식에 더 많이 투자한다', '60/40은 채권 비중이 낮다', 1, '60/40은 자본의 60%를 주식, 40%를 채권에 배분하지만 주식의 변동성이 채권보다 훨씬 높아 포트폴리오 위험의 90% 이상이 주식에서 나온다. 리스크 패리티는 이를 균형화한다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 19, '07', '칼마비율', '칼마비율(Calmar Ratio)의 계산식은?', '샤프비율 / MDD', 'CAGR / |MDD|', '수익률 / 표준편차', '초과수익률 / 하방변동성', 1, '칼마비율 = CAGR / |MDD|로 단위 최대낙폭당 연평균 복합 성장률을 나타내며 특히 MDD 관리가 중요한 투자 전략 평가에 활용된다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (5, 20, '07', '역변동성', '역변동성(Inverse Volatility) 전략이란?', '변동성이 높은 자산에 더 많이 투자', '각 자산의 변동성에 반비례하여 비중을 배분하는 방법', '변동성을 무시하고 균등 배분', '레버리지를 최대화하는 방법', 1, '역변동성 전략은 각 자산의 변동성(표준편차) 역수에 비례하여 비중을 설정하여 변동성이 낮은 자산에 더 높은 비중을 부여하는 간단한 리스크 패리티 접근법이다.');

-- SELECT day, COUNT(*) AS cnt FROM quiz_questions GROUP BY day ORDER BY day;
-- 각 파트별 20건, 총 100건 확인
